# defaults commands
CC=cc
RM=rm -f
INSTALL=install
INSTALL_PROGRAM=$(INSTALL) -s -m 555
INSTALL_DIR=$(INSTALL) -d
INSTALL_LIB=$(INSTALL) -s -m 444
INSTALL_DATA=$(INSTALL) -m 444
INSTALL_SCRIPT=$(INSTALL_PROGRAM)
XGETTEXT=xgettext
MSGFMT=msgfmt
MKDIR=mkdir
CP=cp
